---
title: "*Value of a statistical model based on four kallikrein markers in blood, commercially available as 4Kscore, in all reasonable prostate biopsy subgroups*"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Supplemental Material
Several guideline groups have criticized the 4Kscore data on the basis of the patients included in the studies. The argument offered is to state a particular definition of eligible patients, note that the eligibility criteria for the clinical studies were not identical to that definition and conclude that the research literature is not of value. There are a wide range of reasonable views on what counts as a suitable population for follow-up testing before prostate biopsy and there is little justification for dismissing data from a study because of a reasonable difference of opinion as to eligibility criteria.  To forestall future arguments that data on the 4Kscore can be ignored because they do not meet one or another subjective definition of the eligible or intended use population, we reanalyzed data from a recent individual patient data meta-analysis for every reasonable subgroup.  Only data from completely independent validation studies were included, a total of 8,323 biopsied patients in eight cohorts: Finnish ERSPC round 1, Finnish ERSPC rounds 2 and 3, Göteborg ERSPC round 2, OPKO’s prospective US trial, Rotterdam ERSPC rounds 2 and 3, Tarn ERSPC, Malmö community based cohort (UPCA) and Veterans Affairs. The base model consisted of age, total PSA and DRE result, if available. The lower limit of the PSA range was varied from PSA of 0, 1, 1.5, 2, 2.5, 3 and 4 ng/ml, with the upper limit as 10, 20, 25 and 100 ng/ml, both irrespective of DRE and in patients that are DRE negative only. We also included patients of any age, or restricted to age ranges starting at 40, 45, 50 and 55, and ending at 69, 75, 80 and 90. There were no patients aged younger than 40 or older than 90. These meta-analyses were also run in each subgroup using only contemporary cohorts (OPKO, UPCA and Veterans Affairs). Cohorts were excluded from any given analysis if there were fewer than 20 high-grade cancers or fewer than 20 patients without high-grade cancer.  Results from these 1,792 different analyses – reflecting different combinations of age range, PSA range and DRE status -  are provided below.  

Use the drop down menus to select a PSA range, age range, DRE status, and contemporary cohort indicator and view the results of the meta-analyses for the selected group.  

<iframe id="example1" src="https://sjobergd.shinyapps.io/Kallikrein-Meta-Analysis-App/" style="border: none; width: 100%; height: 8500px" frameborder="0"></iframe>
